name: nanopi-air
version: 16-0.1
summary: NanoPi NEO Air
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core image for the NanoPi NEO Air.
type: gadget
architectures:
  - armhf
confinement: strict
grade: stable

parts:
  uboot:
    plugin: make
    source: git://git.denx.de/u-boot.git
    source-branch: v2017.05
    artifacts: [u-boot-sunxi-with-spl.bin]
    prepare: |
      set -e
      git apply ../../../uboot.patch
      if [ "$(arch)" = "x86_64" ]; then
        TCHAINVER="$(wget -q -O - \
                   https://releases.linaro.org/components/toolchain/binaries/latest/arm-linux-gnueabihf/| \
                   html2text -width 200|grep 'x86_64_arm-linux-gnueabihf.tar.xz '|cut -d' ' -f2)"
        wget https://releases.linaro.org/components/toolchain/binaries/latest/arm-linux-gnueabihf/$TCHAINVER
        tar xf $TCHAINVER
        mv $(echo $TCHAINVER|sed 's/.tar.xz$//') toolchain
        CROSS_COMPILE=$(pwd)/toolchain/bin/arm-linux-gnueabihf- make nanopi_neo_air_defconfig
      else
        make nanopi_neo_air_defconfig
      fi
    build: |
      set -e
      if [ "$(arch)" = "x86_64" ]; then
        CROSS_COMPILE=$(pwd)/toolchain/bin/arm-linux-gnueabihf- make
      else
        make
      fi
    install: |
      set -e
      cp u-boot-sunxi-with-spl.bin $SNAPCRAFT_PART_INSTALL/
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      ln -s uboot.env $SNAPCRAFT_PART_INSTALL/uboot.conf
    build-packages:
      - bc
      - build-essential
      - device-tree-compiler
      - html2text
      - libpython2.7-dev
      - python-minimal
      - wget
